### ISSUE TITLE
Missed favicon.ico

### ISSUE THREAD

**Issue by StepanBakshayev** [wormer/funrun#2]
Please, add favicon.ico. Or I should more correct to say paint icon of the site.

**Comment by wormer** [comment]
Done

2016-06-28 15:44 GMT+06:00 StepanBakshayev <notifications@github.com>:

> Please, add favicon.ico. Or I should more correct to say paint icon of the
> site.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/wormer/funrun/issues/2>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAE89dXLJdc3z-DdnC6wUkTpRrJd7bblks5qQO0IgaJpZM4I_7Ct>
> .
>



-- 
wormer

**Comment by StepanBakshayev** [comment]
Please, add number of issue in commit next time.
